

---
title: "upload_code"
author: "ME"
date: "2025-10-08"
output: html_document
---

# Joining the data
```{r}
library(tidyverse)
library(lubridate)
library(dplyr)
```

# Load in Datasets
```{r}

mortality_race <- read.csv("mortality_race.CSV")
breast_cancer <- read.csv("breast_cancer_clean.csv")
breast_cancer_deaths <- read.csv("breast_cancer_death_clean.csv")
cervical_cancer <- read.csv("cervical_cancer_clean.csv")
cervical_cancer_deaths <- read.csv("cervical_cancer_deaths_clean.csv")
diabetes <- read.csv("diabetes_clean.csv")
heart_disease <- read.csv("heart_disease_clean.csv")
mental_health <- read.csv("mental_health_clean.csv")
```

# Rename State Columns
```{r}
mortality_race <- mortality_race %>%
  rename(state = location_name)

breast_cancer <- breast_cancer %>%
  rename(state = Location)

breast_cancer_deaths <- breast_cancer_deaths%>%
  rename(state = Location)

cervical_cancer <- cervical_cancer %>%
  rename(state = Location)

cervical_cancer_deaths <- cervical_cancer_deaths %>%
  rename(state = Location)

diabetes <- diabetes%>%
  rename(state = Location)

heart_disease  <- heart_disease  %>%
  rename(state = Location)

mental_health <- mental_health %>%
  rename(state = Location)

```


#Rename Race Columns

```{r}
#Mortality

mortality_race <- mortality_race %>%
  rename(race = race_group)

mortality_race$race <- 
  factor(mortality_race$race, 
         levels = c("Hispanic and any race", 
                    "Non-Hispanic American Indian and Alaska Native", 
                    "Non-Hispanic Asian, Native Hawaiian, or Other Pacific Islander",
                    "Non-Hispanic Black",
                    "Non-Hispanic White"),
         labels = c("Hispanic",
                    "American Indian and Alaska Native",
                    "Asian or Native Hawaiian",
                    "Black",
                    "White"))


#Breast Cancer
breast_cancer <- breast_cancer %>%
  rename(Asian_NativeHawaiian = Asian.Native.Hawaiian.or.Pacific.Islander,
         AmericanIndian_AlaskaNative = American.Indian.or.Alaska.Native)

#Breast Cancer Deaths
breast_cancer_deaths$Asian <- as.numeric(breast_cancer_deaths$Asian)
breast_cancer_deaths$Native.Hawaiian.Pacific.Islander <- as.numeric(breast_cancer_deaths$Native.Hawaiian.Pacific.Islander)

breast_cancer_deaths$Asian_NativeHawaiian <- breast_cancer_deaths$Asian + breast_cancer_deaths$Native.Hawaiian.Pacific.Islander

breast_cancer_deaths$Asian <- as.numeric(breast_cancer_deaths$Asian)
breast_cancer_deaths$Native.Hawaiian.Pacific.Islander <- as.numeric(breast_cancer_deaths$Native.Hawaiian.Pacific.Islander)

breast_cancer_deaths <- breast_cancer_deaths%>%
  rename(AmericanIndian_AlaskaNative = American.Indian.or.Alaska.Native)

#Cervical Cancer
cervical_cancer <- cervical_cancer %>%
  rename(Asian_NativeHawaiian = Asian.Native.Hawaiian.or.Pacific.Islander,
         AmericanIndian_AlaskaNative = American.Indian.or.Alaska.Native)


#Cervical Cancer Deaths
cervical_cancer_deaths$Asian <- as.numeric(cervical_cancer_deaths$Asian)
cervical_cancer_deaths$Native.Hawaiian.Pacific.Islander <- as.numeric(cervical_cancer_deaths$Native.Hawaiian.Pacific.Islander)

cervical_cancer_deaths$Asian_NativeHawaiian <- cervical_cancer_deaths$Asian + cervical_cancer_deaths$Native.Hawaiian.Pacific.Islander

cervical_cancer_deaths <- cervical_cancer_deaths%>%
  rename(AmericanIndian_AlaskaNative = American.Indian.or.Alaska.Native)

#Diabetes
diabetes$Asian <- as.numeric(diabetes$Asian)
diabetes$Native.Hawaiian.Pacific.Islander <- as.numeric(diabetes$Native.Hawaiian.Pacific.Islander)

diabetes$Asian_NativeHawaiian <- diabetes$Asian + diabetes$Native.Hawaiian.Pacific.Islander

diabetes <- diabetes%>%
  rename(AmericanIndian_AlaskaNative = American.Indian.or.Alaska.Native)

#Heart Disease
heart_disease$Asian <- as.numeric(heart_disease$Asian)
heart_disease$Native.Hawaiian.Pacific.Islander <- as.numeric(heart_disease$Native.Hawaiian.Pacific.Islander)

heart_disease$Asian_NativeHawaiian <- heart_disease$Asian + heart_disease$Native.Hawaiian.Pacific.Islander

heart_disease <- heart_disease%>%
  rename(AmericanIndian_AlaskaNative = American.Indian.or.Alaska.Native)

#Mental Health
mental_health <- mental_health %>%
  rename(Asian_NativeHawaiian = Asian..Native.Hawaiian.or.Pacific.Islander,
         AmericanIndian_AlaskaNative = American.Indian...Alaska.Native,
         Overall = All.Women)

```

#Make Race Columns Numeric
```{r}

breast_cancer <- breast_cancer %>% 
  mutate_at(c("White",
           "Black",
           "Hispanic",
           "AmericanIndian_AlaskaNative",
           "Asian_NativeHawaiian",
           "Overall"),
         as.numeric)

breast_cancer_deaths <- breast_cancer_deaths %>% 
  mutate_at(c("White",
           "Black",
           "Hispanic",
           "AmericanIndian_AlaskaNative",
           "Asian_NativeHawaiian",
           "Overall"),
         as.numeric)

cervical_cancer <- cervical_cancer %>% 
  mutate_at(c("White",
           "Black",
           "Hispanic",
           "AmericanIndian_AlaskaNative",
           "Asian_NativeHawaiian",
           "Overall"),
         as.numeric)

cervical_cancer_deaths <- cervical_cancer_deaths %>% 
  mutate_at(c("White",
           "Black",
           "Hispanic",
           "AmericanIndian_AlaskaNative",
           "Asian_NativeHawaiian",
           "Overall"),
         as.numeric)

diabetes <- diabetes %>% 
  mutate_at(c("White",
           "Black",
           "Hispanic",
           "AmericanIndian_AlaskaNative",
           "Asian_NativeHawaiian",
           "Overall"),
         as.numeric)

heart_disease <- heart_disease %>% 
  mutate_at(c("White",
           "Black",
           "Hispanic",
           "AmericanIndian_AlaskaNative",
           "Asian_NativeHawaiian",
           "Overall"),
         as.numeric)

mental_health <- mental_health %>% 
  mutate_at(c("White",
           "Black",
           "Hispanic",
           "AmericanIndian_AlaskaNative",
           "Asian_NativeHawaiian",
           "Overall"),
         as.numeric)


```

#Tidying the Data

```{r}
#Breast Cancer
breast_cancer_long <- breast_cancer %>%
  pivot_longer(c("White", 
                 "Black", 
                 "Hispanic",
                 "Asian_NativeHawaiian",
                 "AmericanIndian_AlaskaNative",
                 "Overall"),
               names_to = "race", 
               values_to = "breast_cancer")


#Breast Cancer Deaths
breast_cancer_deaths_long <- breast_cancer_deaths %>%
  pivot_longer(c("White", 
                 "Black", 
                 "Hispanic",
                 "Asian_NativeHawaiian",
                 "AmericanIndian_AlaskaNative",
                 "Overall"),
               names_to = "race", 
               values_to = "breast_cancer_deaths")

#Cervical Cancer
cervical_cancer_long <- cervical_cancer %>%
  pivot_longer(c("White", 
                 "Black", 
                 "Hispanic",
                 "Asian_NativeHawaiian",
                 "AmericanIndian_AlaskaNative",
                 "Overall"),
               names_to = "race", 
               values_to = "cervical_cancer")


#Cervical Cancer Deaths
cervical_cancer_deaths_long <- cervical_cancer_deaths %>%
  pivot_longer(c("White", 
                 "Black", 
                 "Hispanic",
                 "Asian_NativeHawaiian",
                 "AmericanIndian_AlaskaNative",
                 "Overall"),
               names_to = "race", 
               values_to = "cervical_cancer_deaths")

#Diabetes
diabetes_long <- diabetes %>%
  pivot_longer(c("White", 
                 "Black", 
                 "Hispanic",
                 "Asian_NativeHawaiian",
                 "AmericanIndian_AlaskaNative",
                 "Overall"),
               names_to = "race", 
               values_to = "diabetes")

#Heart Disease
heart_disease_long <- heart_disease %>%
  pivot_longer(c("White", 
                 "Black", 
                 "Hispanic",
                 "Asian_NativeHawaiian",
                 "AmericanIndian_AlaskaNative",
                 "Overall"),
               names_to = "race", 
               values_to = "heart_disease")

#Mental Health
mental_health_long <- mental_health %>%
  pivot_longer(c("White", 
                 "Black", 
                 "Hispanic",
                 "Asian_NativeHawaiian",
                 "AmericanIndian_AlaskaNative",
                 "Overall"),
               names_to = "race", 
               values_to = "mental_health")


```

#Select Necessary Columns
```{r}
breast_cancer_deaths_long <-
  breast_cancer_deaths_long %>%
  select("state",
         "race",
         "breast_cancer_deaths")

cervical_cancer_deaths_long <-
 cervical_cancer_deaths_long %>%
  select("state",
         "race",
         "cervical_cancer_deaths")

diabetes_long <-
 diabetes_long %>%
  select("state",
         "race",
         "diabetes")

heart_disease_long <-
  heart_disease_long %>%
  select("state",
         "race",
         "heart_disease")

mental_health_long <-
  mental_health_long %>%
  select("state",
         "race",
         "mental_health")

mortality_race_long <-
  mortality_race %>%
  select("state",
         "race",
         "val") %>%
  rename(maternal_mortality = val)

```





```{r}

health_join <-
  breast_cancer_long %>%
  left_join(breast_cancer_deaths_long,
            by = c("state", "race")) %>%
  left_join(cervical_cancer_long,
            by = c("state", "race"))  %>%
  left_join(cervical_cancer_deaths_long,
            by = c("state", "race")) %>%
  left_join(diabetes_long,
            by = c("state", "race"))  %>%
  left_join(heart_disease_long,
            by = c("state", "race"))  %>%
  left_join(mental_health_long,
            by = c("state", "race"))  %>%
  left_join(mortality_race_long,
            by = c("state", "race")) 


health_long <- health_join %>%
  pivot_longer(c("breast_cancer", 
                 "breast_cancer_deaths", 
                 "cervical_cancer", 
                 "cervical_cancer_deaths",
                 "diabetes",
                 "heart_disease",
                 "mental_health",
                 "maternal_mortality"),
               names_to = "health_condition", 
               values_to = "incidence")

health_long_clean <- 
  health_long[!is.na(health_long$incidence),]



```

```{r}
library(shiny)      # Load Shiny
library(dplyr)      # Load dplyr for data manipulation (filter, join, etc.)
library(DT)         # Load DT for interactive tables
library(leaflet)    # Load leaflet for maps
library(sf)         # Load sf package to work with spatial/geographic data
library(htmltools)  # Load htmltools to create HTML formatted labels

# Load your data (runs once when app starts, before server function)
states <- read_sf("us-states.geojson")  # Read the geojson file with state boundaries
# breast_cancer_long <- read.csv("your_file.csv")  # Load your breast cancer data

server <- function(input, output, session) {
  # input: contains values from UI controls (like dropdown selections)
  # output: where you send results to display in UI
  # session: information about the current user session
  
  # Update the race dropdown with actual races from your data
  updateSelectInput(session,                    # Which session to update
                    "race_filter",              # Which input to update (the dropdown ID)
                    choices = c("All", unique(breast_cancer_long$race)))  
                    # Gets all unique races from your data and adds "All" option
  
  # REACTIVE DATA - This recalculates automatically when race_filter changes
  filtered_data <- reactive({
    # reactive({...}) creates code that "listens" for changes in inputs
    
    result <- breast_cancer_long  # Start with full dataset
    
    if (input$race_filter != "All") {  # If user selected a specific race
      result <- result %>%              # Take the result and...
        filter(race == input$race_filter)  # Keep only rows matching selected race
    }
    # If "All" is selected, no filtering happens
    
    result  # Return the filtered (or unfiltered) data
  })
  
  # REACTIVE MAP DATA - Joins geography with filtered cancer data
  map_data <- reactive({
    # This also recalculates when filtered_data() changes
    
    states %>%                           # Start with state boundaries
      left_join(filtered_data(),         # Combine with filtered cancer data
                by = c("name" = "state")) # Match state names in geojson with
                                          # state column in cancer data
    # left_join keeps all states even if no cancer data exists for them
  })
  
  # RENDER THE MAP - Creates the actual map visualization
  output$cancer_map <- renderLeaflet({
    # renderLeaflet tells Shiny this is a map output
    # Automatically re-runs when map_data() changes
    
    data <- map_data()  # Get the current joined data
    
    # Define bins (ranges) for coloring the map
    bins <- c(0, 50, 100, 150, 200, 250, 300, 350, Inf)
    # States with rates 0-50 get one color, 50-100 another, etc.
    # Inf means "infinity" - catches any value above 350
    
    # Create color palette
    pal <- colorBin("RdPu",                    # Red-Purple color scheme
                    domain = data$breast_cancer_rate,  # Values to color
                    bins = bins)               # Use the bins defined above
    
    # Create hover labels (popup text when you mouse over states)
    labels <- sprintf(
      "<strong>%s</strong><br/>%g breast cancer rate",  
      # sprintf formats text: %s = string, %g = number, <br/> = line break
      data$name,                  # State name
      data$breast_cancer_rate     # Cancer rate number
    ) %>% lapply(HTML)            # Convert to HTML format for display
    
    # BUILD THE MAP
    leaflet(data) %>%             # Start with the data
      setView(-96, 37.8, 4) %>%   # Center map: longitude -96, latitude 37.8, zoom 4
                                   # This centers on middle of US
      
      addProviderTiles("CartoDB.Positron") %>%  # Add background map tiles (base map)
                                                 # CartoDB.Positron is light/minimal style
      
      addPolygons(                # Add the state shapes
        fillColor = ~pal(breast_cancer_rate),  # Color states by cancer rate
                                                # ~ means "use this column from data"
        
        weight = 2,               # Border thickness (2 pixels)
        opacity = 1,              # Border opacity (1 = fully opaque)
        color = "white",          # Border color
        dashArray = "3",          # Border style (3 = small dashes)
        fillOpacity = 0.7,        # State fill transparency (0.7 = 70% opaque)
        
        highlightOptions = highlightOptions(  # What happens when you hover over a state
          weight = 5,             # Border gets thicker
          color = "#666",         # Border turns gray
          dashArray = "",         # Border becomes solid (not dashed)
          fillOpacity = 0.7,      # Fill opacity stays same
          bringToFront = TRUE),   # Bring hovered state to front
        
        label = labels,           # Attach the labels we created
        labelOptions = labelOptions(  # Style the labels
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "15px",      # Font size
          direction = "auto")) %>%  # Label position adjusts automatically
      
      addLegend(                  # Add color legend
        pal = pal,                # Use same color palette
        values = ~breast_cancer_rate,  # Show range of cancer rates
        opacity = 0.7,            # Legend transparency
        title = "Breast Cancer Rate",  # Legend title
        position = "bottomright") # Put legend in bottom right corner
  })
  
  # RENDER THE TABLE - Creates interactive data table
  output$cancer_table <- renderDT({
    # renderDT tells Shiny this is a DT table output
    
    datatable(filtered_data(),    # Use the filtered data
              options = list(
                pageLength = 10,  # Show 10 rows per page
                scrollX = TRUE),  # Allow horizontal scrolling if table is wide
              rownames = FALSE)   # Don't show row numbers
  })
  
  # RENDER SUMMARY STATISTICS - Creates text summary
  output$summary_stats <- renderPrint({
    # renderPrint captures text output (like from cat() or print())
    
    data <- filtered_data()       # Get current filtered data
    
    # cat() prints text to output
    cat("Number of observations:", nrow(data), "\n")  # Count rows, \n = new line
    cat("Race filter:", input$race_filter, "\n")      # Show selected race
    cat("Average breast cancer rate:", 
        round(mean(data$breast_cancer_rate, na.rm = TRUE), 2), "\n")
        # mean() = average, na.rm = TRUE ignores missing values, round to 2 decimals
    cat("Min rate:", 
        round(min(data$breast_cancer_rate, na.rm = TRUE), 2), "\n")  # Minimum
    cat("Max rate:", 
        round(max(data$breast_cancer_rate, na.rm = TRUE), 2), "\n")  # Maximum
  })
}
```

