---
title: "test_chlamydia_year_join"
output: html_document
---

# Joining the data
```{r}
library(tidyverse)
library(lubridate)
library(dplyr)
```

# Load in Datasets
```{r}
chlamydia19 <- read.csv("2019_chlamydia.csv")
chlamydia20 <- read.csv("2020_chlamydia.csv")
chlamydia21 <- read.csv("2021_chlamydia.csv")
chlamydia22 <- read.csv("2022_chlamydia.csv")
chlamydia23 <- read.csv("2023_chlamydia.csv")
```

# Rename State Columns
```{r}
chlamydia19 <- chlamydia19 %>%
  rename(state = Location)

chlamydia20 <- chlamydia20 %>%
  rename(state = Location)

chlamydia21 <- chlamydia21%>%
  rename(state = Location)

chlamydia22 <- chlamydia22 %>%
  rename(state = Location)

chlamydia23 <- chlamydia23 %>%
  rename(state = Location)

```

# rename race columns
```{r}
chlamydia20 <- chlamydia20%>%
  rename(Black = Black.African.American,
         Hispanic = Hispanic.Latino,
         AmericanIndian_AlaskaNative = American.Indian.Alaska.Native,
         Overall = Total)

chlamydia21 <- chlamydia21%>%
  rename(Black = Black.African.American,
         Hispanic = Hispanic.Latino,
         AmericanIndian_AlaskaNative = American.Indian.Alaska.Native,
         Overall = Total)

chlamydia22 <- chlamydia22 %>%
  rename(Black = Black.African.American,
         Hispanic = Hispanic.Latino,
         AmericanIndian_AlaskaNative = American.Indian.Alaska.Native,
         Overall = Total)

chlamydia23 <- chlamydia23 %>%
  rename(Black = Black.African.American,
         Hispanic = Hispanic.Latino,
         AmericanIndian_AlaskaNative = American.Indian.Alaska.Native,
         Overall = Total)
```

# add a year column
```{r}
library(dplyr)
chlamydia19y <- chlamydia19 %>%
  mutate(year = 2019)

chlamydia20y <- chlamydia20 %>%
  mutate(year = 2020)

chlamydia21y <- chlamydia21 %>%
  mutate(year = 2021)

chlamydia22y <- chlamydia22 %>%
  mutate(year = 2022)

chlamydia23y <- chlamydia23 %>%
  mutate(year = 2023)
```

# deleting footnote column
```{r}
chlamydia19y$Footnotes <- NULL
chlamydia20y$Footnotes <- NULL
chlamydia21y$Footnotes <- NULL
chlamydia22y$Footnotes <- NULL
chlamydia23y$Footnotes <- NULL

```

# convert numeric
```{r}
# Convert all race columns to numeric first
chlamydia20y <- chlamydia20y %>%
  mutate(across(c(White, Black,Hispanic,
                 AmericanIndian_AlaskaNative,Asian,Native.Hawaiian.or.Pacific.Islander,Multiple.races, Overall), 
                as.numeric))

chlamydia21y <- chlamydia21y %>%
  mutate(across(c(White, Black,Hispanic,
                 AmericanIndian_AlaskaNative,Asian,Native.Hawaiian.or.Pacific.Islander,Multiple.races, Overall), 
                as.numeric))

chlamydia22y <- chlamydia22y %>%
  mutate(across(c(White, Black,Hispanic,
                 AmericanIndian_AlaskaNative,Asian,Native.Hawaiian.or.Pacific.Islander,Multiple.races, Overall), 
                as.numeric))

chlamydia23y <- chlamydia23y %>%
  mutate(across(c(White, Black,Hispanic,
                 AmericanIndian_AlaskaNative,Asian,Native.Hawaiian.or.Pacific.Islander,Multiple.races, Overall), 
                as.numeric))
```



# Tidy Long
```{r}
chlamydia20_long <- chlamydia20y %>%
  pivot_longer(c("White", 
                 "Black", 
                 "Hispanic",
                 "AmericanIndian_AlaskaNative",
                 "Asian",
                 "Native.Hawaiian.or.Pacific.Islander",
                 "Multiple.races",
                 "Overall"),
               names_to = "race", 
               values_to = "chlamydia")

chlamydia21_long <- chlamydia21y %>%
  pivot_longer(c("White", 
                 "Black", 
                 "Hispanic",
                 "AmericanIndian_AlaskaNative",
                 "Asian",
                 "Native.Hawaiian.or.Pacific.Islander",
                 "Multiple.races",
                 "Overall"),
               names_to = "race", 
               values_to = "chlamydia")

chlamydia22_long <- chlamydia22y %>%
  pivot_longer(c("White", 
                 "Black", 
                 "Hispanic",
                 "AmericanIndian_AlaskaNative",
                 "Asian",
                 "Native.Hawaiian.or.Pacific.Islander",
                 "Multiple.races",
                 "Overall"),
               names_to = "race", 
               values_to = "chlamydia")

chlamydia23_long <- chlamydia23y %>%
  pivot_longer(c("White", 
                 "Black", 
                 "Hispanic",
                 "AmericanIndian_AlaskaNative",
                 "Asian",
                 "Native.Hawaiian.or.Pacific.Islander",
                 "Multiple.races",
                 "Overall"),
               names_to = "race", 
               values_to = "chlamydia")
```

#Select Necessary Columns
```{r}
chlamydia20y_long <-
  chlamydia20_long %>%
  select("state",
         "year",
         "race",
         "chlamydia")

chlamydia21y_long <-
  chlamydia21_long %>%
  select("state",
         "year",
         "race",
         "chlamydia")

chlamydia22y_long <-
  chlamydia22_long %>%
  select("state",
         "year",
         "race",
         "chlamydia")

chlamydia23y_long <-
  chlamydia23_long %>%
  select("state",
         "year",
         "race",
         "chlamydia")
```

# Bind rows
```{r}
chlamydia_all_long <- bind_rows(
  chlamydia20y_long,
  chlamydia21y_long,
  chlamydia22y_long,
  chlamydia23y_long
)
```



